function [perm_stat, permzs] = permute_zs(zs, nrep, varargin)

pnames = {'niter', ...
    'clip_range', ...
    'metric', ...
    'group_by',...
    'clip_low_wt', ...
    'clip_low_cc', ...
    'cid_prefix', ...
    'modz_metric',...
    'ssn'};
dflts = {1, ...
    [-10, 10], ...
    'modz', ...
    'pert_id',...
    true, ...
    true, ...
    '', ...
    'wt_avg',...
    100};

args = parse_args(pnames, dflts, varargin{:});
[nr, nc] = size(zs.mat);
permzs = mkgctstruct(zeros(nr, args.niter), ...
    'rid', zs.rid, ....
    'rhd', zs.rhd, ...
    'rdesc', zs.rdesc, ...
    'cid', gen_labels(args.niter));
cc_q75 = zeros(args.niter, 1);
distil_ids = cell(args.niter, 1);

[cn, nl] = getcls(ds_get_meta(zs, 'column', args.group_by));
pert_dict = containers.Map(1:nc, nl);
for ii=1:args.niter
    cidx = randsample(nc, nrep);

    %store distil_ids
    distil_ids{ii} = print_dlm_line(zs.cid(cidx), 'dlm', '|');

    [permzs.mat(:, ii), samp_wt, cc] = distil_core(zs.mat(:, cidx), ...
        args.metric,...
         1:nr, ...
        args.clip_low_wt, ...
        args.clip_low_cc, ...
        args.modz_metric);
    cc_q75(ii) = prctile(tri2vec(cc), 75);
end

ss = sig_strength(permzs.mat, 'n', args.ssn);
permzs = ds_add_meta(permzs, 'column', {'sig_strength', 'cc_q75'}, num2cell([ss, cc_q75]));

% Add distil_ids as column metadata
permzs = ds_add_meta(permzs, 'column', {'distil_id'}, distil_ids);

% Stats
perm_stat = permute_stat(permzs);
end
