function [ds_cc,ds_rank,ds_cc_lincs,ds_rank_lincs,ds_median,ds_median_lincs, ...
    cc_sorted_median, cc_sorted_median_table, cc_sorted_median_lincs, ...
    cc_sorted_median_lincs_table] = calculate_cc_and_rank(det_plate,...
    ds_plate,ds_ref_lm, cell_ids_annot_all,cell_id_annot, lincs_lines)
%% Function calculate_cc_and_rank
% A helper function to calculates cc and ranks in the dactyloscopy_single 
% function. This function was created to facilitate testing.
%
% Slice the matrix to have only columns with a unique cell line
ds_plate_slice_unique_cell_line = ds_slice(ds_plate,...
    'cid',ds_plate.cid(ismember(cell_ids_annot_all, cell_id_annot)));

% Create a gct structure with correlation coefficient
ds_cc = mkgctstruct(...
    fastcorr(ds_ref_lm.mat,ds_plate_slice_unique_cell_line.mat,'type','spearman'),...
    'rid',ds_ref_lm.cid,'rhd',ds_ref_lm.chd,'rdesc',ds_ref_lm.cdesc,...
    'cid',ds_plate_slice_unique_cell_line.cid, 'chd',ds_plate_slice_unique_cell_line.chd,...
    'cdesc',ds_plate_slice_unique_cell_line.cdesc);

% Create a gct structure with ranks
ds_rank = ds_cc;
ds_rank.mat = rankorder(ds_cc.mat,'direc','descend','dim',1,...
    'fixties',false);

% Create a gct structure with cc and with LINCS lines
ds_cc_lincs =  ds_slice(ds_cc,'rid',lincs_lines);

% Create a gct structure with ranks and with LINCS lines
ds_rank_lincs = ds_cc_lincs;
ds_rank_lincs.mat = rankorder(ds_cc_lincs.mat,'direc','descend',...
    'dim',1,'fixties',false);

% Construct additional gct structures
cid = {'rank_from_median_cc','rank_from_median_rank','cc_median','cc_mean'};
ds_median = mkgctstruct([rankorder(median(ds_cc.mat,2),'direc','descend','fixties',false),...
    median(ds_rank.mat,2),median(ds_cc.mat,2),mean(ds_cc.mat,2)],...
    'rid',ds_cc.rid,'rhd',ds_cc.rhd,'rdesc',ds_cc.rdesc,...
    'cid',cid,...
    'chd', {'det_plate'},...
    'cdesc',repmat(det_plate,length(cid),1));

ds_median_lincs = mkgctstruct([rankorder(median(ds_cc_lincs.mat,2),'direc','descend','fixties',false),...
    median(ds_rank_lincs.mat,2),median(ds_cc_lincs.mat,2),mean(ds_cc_lincs.mat,2)],...
    'rid',ds_cc_lincs.rid,'rhd',ds_cc_lincs.rhd,'rdesc',ds_cc_lincs.rdesc,...
    'cid',cid,...
    'chd', {'det_plate'},...
    'cdesc',repmat(det_plate,length(cid),1));

cc_sorted_median = sortrows([ds_median.rid, ds_get_meta(ds_median,...
    'row',{'cell_histology','cell_lineage'}),...
    num2cell(ds_median.mat)],4);
cc_sorted_median_table = cell2table(cc_sorted_median,'VariableNames',...
    {'cell_id','cell_histology','cell_lineage','rank_from_median_cc',...
    'rank_from_median_rank','cc_median','cc_mean'});

cc_sorted_median_lincs = sortrows([ds_median_lincs.rid, ...
    ds_get_meta(ds_median_lincs,'row',{'cell_histology','cell_lineage'}),...
    num2cell(ds_median_lincs.mat)],4);

cc_sorted_median_lincs_table = cell2table(cc_sorted_median_lincs,'VariableNames',...
    {'cell_id','cell_histology','cell_lineage','rank_from_median_cc',...
    'rank_from_median_rank','median','mean'});
end
