function yn = isvalidTableName_(table_name)
% Check if table_name is valid
yn = isempty(regexp(table_name, '^sqlite_', 'once')) && ...
    ~isempty(regexp(table_name, '^[a-zA-Z][a-zA-Z0-9_]*$', ...
    'once')) && ...
    ~mortar.containers.Sqlite.keywords.isKey(upper(table_name));
end
