function ds = fix_merged_meta(ds)
% FIX_MERGED_META Fix annotations in a merged dataset. 

% row annotations to delete
delfn = {'pr_analyte_id';...
    'pr_analyte_num';...
    'pr_bset_id';...
    'pr_gene_seq';...
    'pr_lua_id';...
    'pr_lua_seq';...
    'pr_pool_id';...
    'pr_is_lmark'};

ds = ds_delete_meta(ds, 'row', delfn);

end