function combods = merge_profile(dsfile, varargin)
% MERGE_PROFILE Merge datasets.
%   COMBODS = MERGE_PROFILE(DSFILES) Merges a list of GCT(x) files, where DSFILES
%   is a cell array of paths to the files and COMBODS is the merged result.

%TODO: Report collisions

pnames = {'cid', 'rid', 'exclude_cid',...
          'row_filter', 'column_filter',...
          'exclude_rid', 'fix_meta', 'skip_annot',...
          'merge_direction', 'merge_partial', 'missing_value',...
          'verbose'};
dflts = {'', '', false,...
         '', '',...
         false, false, false,...
         'auto-determine', false, nan,...
         false};
args = parse_args(pnames, dflts, varargin{:});

if ~isempty(args.cid)
    args.cid = parse_grp(args.cid);
end

if ~iscell(dsfile)
    error('Expected cell array as input');
end
nds = length(dsfile);
tmpds = parse_gctx(dsfile{1}, 'skip_annot', args.skip_annot);
combods = ds_slice(tmpds, 'cid', args.cid,...
          'rid', args.rid, 'exclude_cid', args.exclude_cid,...
          'exclude_rid', args.exclude_rid,...
          'row_filter', args.row_filter,...
          'column_filter', args.column_filter,...
          'ignore_missing', true);

for ii=2:nds    
  
  tmpds = parse_gctx(dsfile{ii}, 'skip_annot', args.skip_annot);
  fprintf ('%d/%d %s\n', ii, nds, tmpds.src);
  tmpds = ds_slice(tmpds, 'cid', args.cid,...
            'rid', args.rid, 'exclude_cid', args.exclude_cid,...
            'exclude_rid', args.exclude_rid,...
            'row_filter', args.row_filter,...
            'column_filter', args.column_filter,...
            'ignore_missing', true);
  if ~isempty(tmpds.mat)
    combods = merge_two(combods, tmpds,...
        'merge_direction', args.merge_direction, 'merge_partial',...
        args.merge_partial, 'missing_value', args.missing_value,...
        'verbose', args.verbose);
  end
end

% sort features
combods = sort_features(combods);

% sort samples
combods = sort_samples(combods);

if args.fix_meta
    % fix extraneous feature fields in merged dataset
    combods = fix_merged_meta(combods);
    % TEMP fix for legacy sample annotations
    combods = fix_sample_meta(combods);
end

end


