function gendoc(lib_path, html_path)
% GENDOC Generate documentation for the Mortar Library
% use Graphviz
% addpath ('ext/m2html')
% gendoc

%  $Author: Rajiv Narayan [narayan@broadinstitute.org]
%  $Date: Oct.22.2010 12:45:40 EDT

% folders to exclude
EXCLUDE_DIR = {'doc','ext','tools','tmp',...
    'unit_tests','resources','+mortar','.svn',...
    'deprecated', 'scratch', 'mongo-matlab-driver',...
    'templates', '.git'};

d = dir(lib_path);
%dirs
fn = {d([d.isdir]).name};
% exclude
fn(strncmp(fn,'.',1)) =[];
fn = setdiff(fn, EXCLUDE_DIR);
m2html ('mfiles', fn, ...
    'htmldir', html_path,...
    'recursive', 'on',...
    'source', 'on',...
    'syntaxhighlighting', 'on',...
    'tabs', 4,...
    'globalHypertextLinks', 'on',...
    'graph', 'off',...
    'save', 'on',...
    'indexfile', 'index',...
    'extension', '.html',...
    'template', 'mortar')