function gendoc(lib_path, html_path)
% GENDOC Generate documentation for the Mortar Library
%
% lib_path = mortarpath;
% html_path = '/path/to/mortar_docs';
% addpath(fullfile(mortarpath, 'ext', 'm2html'));
% gendoc(lib_path, html_path);
%
% Note: Ensure graphviz is installed if the graph option is enabled

%  $Author: Rajiv Narayan [narayan@broadinstitute.org]
%  $Date: Oct.22.2010 12:45:40 EDT

% folders to exclude
EXCLUDE_DIR = {'docs','ext','tmp',...
    'unit_tests','resources','+mortar','.svn',...
    'deprecated', 'scratch', 'mksqlite', 'mongo-matlab-driver',...
    'templates', '.git', '+work', 'tests', 'src', 'toolchain', 'reports', 'js', 'docgen', 'cmapM'};

d = dir(lib_path);
%dirs
fn = {d([d.isdir]).name};
% exclude
fn(strncmp(fn,'.',1)) =[];
fn = setdiff(fn, EXCLUDE_DIR);
fn = strcat(fn, '/');
mkdirnotexist(html_path);
m2html('mfiles', fn, ...
    'htmldir', html_path,...
    'recursive', 'on',...
    'source', 'on',...
    'syntaxhighlighting', 'on',...
    'tabs', 4,...
    'globalHypertextLinks', 'on',...
    'graph', 'off',...
    'save', 'on',...
    'indexfile', 'index',...
    'extension', '.html',...
    'template', 'mortar')
end