function runAnalysis_(obj, varargin)
args = obj.getArgs;
obj.res_ = main(args);
end

function res = main(args)
% Main function
% ADD CORE CODE BELOW
res = struct('args', args);
% res.output = parse_gctx(args.ds);

% run builder
mortar.collate.Brew.build('brew_path', args.brew_path,...
                          'brew_list', args.brew_list,...
                          'brew_group', args.brew_group,...
                          'brew_root', args.brew_root,...
                          'row_filter', args.row_filter,...
                          'column_filter', args.column_filter,...
                          'dose_list', args.dose_list,...
                          'dose_tolerance', args.dose_tolerance,...
                          'feature_id', args.feature_id,...
                          'do_quick_build', args.do_quick_build,...
                          'out', args.out,...
                          'create_subdir', args.create_subdir,...
                          'rpt', args.rpt,...
                          'level_3_file_pattern', args.level_3_file_pattern,...
                          'level_4_file_pattern', args.level_4_file_pattern,...
                          'level_5_file_pattern', args.level_5_file_pattern,...
                          'feature_platform', args.feature_platform,...
                          'feature_space', args.feature_space,...
                          'custom_chip', args.custom_chip);

end
