function stats = describe(x, varargin)
% DESCRIBE Descriptive statistics of a variable.
%   STATS = DESCRIBE(X) returns a structure with the following descriptive
%   statistics of X:
%   n: Number of non NaN elements
%   min: Minimum value
%   max: Maximum value
%   mean: Average value
%   median: Median value
%   std: Standard deviation
%   iqr: Interquartile range
%   mad: Median absolute deviation
%   aad: Mean/Average absolute deviation
%   cv: Coefficient of variation 100*std(x)/mean(x)
%   robcv: Robust C.V. 100*iqr(x)/median(x)
%   fivenum: Five number summary of X: prctile(X, [1, 25, 50, 75, 99])
%   fivenum_p: Percentiles used for fivenum
%   nan: Number of NaNs
%
%   NaN values are excluded before the statistics are computed.

fivenum_p = [1,25,50,75,99];
stats = struct('n', 0,...
    'min', [],...
    'max', [],...
    'mean', [],...
    'median', [],...
    'std', [],...
    'iqr', [],...
    'mad', [],...
    'aad', [],...
    'cv', [],...
    'robcv', [],...
    'fivenum_p', fivenum_p,...
    'fivenum', '',...
    'q75', [],...
    'q25', [],...
    'nan', 0);
if ~isempty(x)
    x = x(:);
    n = length(x);
    nanidx=isnan(x);
    numnan = nnz(nanidx);
    %x = x(~nanidx);
    
    mu = nanmean(x);
    sigma = nanstd(x);
    cvar = 100*sigma/abs(mu);
    p = prctile(x, fivenum_p);
    robcv = 100 * (p(4)-p(2)) / abs(p(3) + eps);
    [minx, minidx] = nanmin(x);
    [maxx, maxidx] = nanmax(x);
    madx = mad(x, 1);
    aadx = mad(x, 0);
    
    stats = struct('n', n,...
        'min', minx,...
        'minidx', minidx,...
        'max', maxx,...
        'maxidx', maxidx,...
        'mean', mu,...
        'median', p(3),...
        'std', sigma,...
        'iqr', p(4)-p(2),...
        'mad', madx,...
        'aad', aadx,...
        'cv', cvar,...
        'robcv', robcv,...
        'fivenum_p', fivenum_p,...
        'fivenum', p,...
        'q75', p(4),...
        'q25', p(2),...
        'nan', numnan);
end
end