function add_velocity_jar(isverbose)
if ~isvarexist('isverbose')
    isverbose = true;
end
% Jar files for Apache Velocity
jarlist ={'antlr-2.7.5.jar';...
    'avalon-logkit-2.1.jar';...
    'commons-collections-3.2.1.jar';...
    'commons-lang-2.4.jar';...
    'commons-lang-2.6.jar';...
    'commons-logging-1.1.jar';...
    'jdom-1.0.jar';...
    'log4j-1.2.12.jar';...
    'maven-ant-tasks-2.0.9.jar';...
    'oro-2.0.8.jar';...
    'servletapi-2.3.jar';...
    'velocity-1.7.jar';...
    'werken-xpath-0.9.4.jar'};
jarpath = fullfile(mortarpath, 'ext/jars');
addjar(jarlist, jarpath, isverbose);
end