function add_excel_jar(isverbose)
if ~isvarexist('isverbose')
    isverbose = true;
end
% Jar files for Apache POI
jarlist = {'poi-3.7-20101029.jar',...
    'poi-ooxml-3.7-20101029.jar',...
    'poi-ooxml-schemas-3.7-20101029.jar',...
    'dom4j-1.6.1.jar',...
    'xmlbeans-2.3.0.jar',...
    'geronimo-stax-api_1.0_spec-1.0.jar'};
jarpath = fullfile(mortarpath, 'ext/jars');
addjar(jarlist, jarpath, isverbose);
end