function rpt = get_lxb_stats(lxb_folder)
% GET_LXB_STATS Compute statistics per analyte from LXB files

[fn, fp] = find_file(fullfile(lxb_folder, '*.lxb'));

nanalyte = 500;
nsample = length(fn);
rid = gen_labels(nanalyte, 'zeropad', false);
cid = fn;
[ir, ic] = find(ones(nanalyte, nsample));

rpt = struct('cid', cid(ic),...
       'rid', rid(ir),...
       'num_bead', nan,...
       'mean_exp', nan,...
       'std_exp', nan,...
       'median_exp', nan,...
       'iqr_exp', nan);
   
for ii=1:nsample
    this_lxb = parse_lxb(fp{ii});    
    keep = this_lxb.RID>0;
    log2_exp = safe_log2(this_lxb.RP1(keep));
    [analyte_id, num_bead, mean_exp, std_exp, median_exp, iqr_exp] =...
        grpstats(log2_exp, this_lxb.RID(keep),...
        {'gname', 'numel', 'nanmean', 'nanstd', 'nanmedian', 'naniqr'});
    rpt_idx = (ii-1)*nanalyte + str2double(analyte_id);
    rpt = setarrayfield(rpt, rpt_idx,...
        {'num_bead', 'mean_exp', 'std_exp', 'median_exp', 'iqr_exp'},...
        num_bead, mean_exp, std_exp, median_exp, iqr_exp);
end

end