%% Run unit-tests for a curated list of sig-tools
tool_list = {'TestSigAnnotate.m',...
 'TestSigCollate.m',...
 'TestSigCurie.m',...
 'TestSigGetGenesets.m',...
 'TestSigGseaPreranked.m',...
 'TestSigGutc.m',... 
 'TestSigIntrospect.m',...
 'TestSigMarker.m',...
 'TestSigPCA.m',... 
 'TestSigQueryl1k.m',...
 'TestSigRecall.m',...
 'TestSigScore2Rank.m',...
 'TestSigSlice.m',...
 'TestSigTSNE.m',... 
 'TestSigTestMLR.m',...
 'TestSigTrainMLR.m',...
 'TestSigZScore.m',...
 };
num_curated = length(tool_list);
% all tests
[test_name, test_path] = find_file(fullfile(mortarpath, 'tests', 'TestSig*.m'));
keep = ismember(test_name, tool_list);
num_found = nnz(keep);
fprintf(1, 'Found tests for %d/%d tools\n', num_found, num_curated);
test_name = test_name(keep);
test_path = test_path(keep);
% run the tests
test_results = runtests(test_path);
% display results
disp(test_results.table)
 
        